### ISSUE TITLE
backticks as a built-in?

### ISSUE THREAD

**Issue by ng-0** [rain-1/s#4]
Would you be open to implement backticks like in tcsh, or similar to es and rc?

My practical use is:

guix size \`guix build s\`

returns the size of the last result (store path) of the command in the backticks, using tcsh.

In 'es' it is done in like this (one way of many):

guix size `{guix build s}

**Comment by rain-1** [comment]
A feature like this is required,

`{} is very nice because it nests well

but I think a primitive like set/unset/source fits more with `s` and doesn't require new parsing code.

`eval <var> <command>`

maybe this could be it? runs the command and puts the stripped result into the env var.

stripped meaning, \x00 removed.  I am not sure what other restrictions there are on env vars.

**Comment by rain-1** [comment]
start of implementing eval: https://github.com/rain-1/s/commit/47ddc3b735f5b3e8375aaa36d85312dd6569ad6b

it is not yet capturing the result into the env var.

**Comment by rain-1** [comment]
https://github.com/rain-1/s/commit/2813e2edb4d0794b78276e2604e9119cc2cda1ec
