### ISSUE TITLE
Need tests

### ISSUE THREAD

**Issue by rain-1** [rain-1/s#6]
Need to make tests for each builtin and feature.

**Comment by edvb** [comment]
I am currently writing some more tests. Can I split `t/` into `test/` and `expect/` directories to house the `.test` and `.expect` files repectivly? Right now `t/` is pretty messy.

Can we also give better names to the different tests other then just incrementing the number at the end?

Maybe instead of using a `t/` direcoty needing a shell scirpt in `sh` we could use something like [clitest](https://github.com/aureliojargas/clitest) to run tests based on examples in a README. I not sure how this would work since this is our own shell, not bash.

**Comment by rain-1** [comment]
Great idea to split the tests into 2 folders. I've done this now: https://github.com/rain-1/s/commit/207a0076b64e880a9377834ec4a02ba052f0f1df

Yes feel free to rename them if you prefer, but naming can be quite hard so don't worry about it too much.

clitest actually looks like a very nice tool - I may use this for other project - but I don't think we will have any scaling problems for now, so lets avoid pulling in a new dependency! I'm fine with our test runner script in `sh`. There is no need to 'dogfood' our shell and write the test runner in `s`.

**Comment by edvb** [comment]
Should the file extension also be modified? `expect/file.expect` and `test/file.test` is a little redundant, maybe just `expect/file.txt` and `test/file.sh`? Also looking back `test/` probably isn't the best name since it is already in the directory `t/` maybe `sh/` or `scripts/` to better label what the files are?

**Comment by rain-1** [comment]
yes, feel free to rename if you prefer!

**Comment by edvb** [comment]
I renamed them, will create pull request shortly. Should I also remove `t/exponen.sh` as it seems unused?

**Comment by rain-1** [comment]
I don't want to outright remove it, it's a "negative test" (produces an error) and our test runner can't cope with that. Maybe we can just put it somewhere for running manually just now.
